### ISSUE TITLE
tab not show

### ISSUE THREAD

**Issue by souce** [dbtek/dbyll#56]
Hi ,I like this theme you made, but I got some problem，
in "categories" page and "tags" page, I can't switch tabs, they are invisible，
I changed <a href="#xxx-ref"> to  <a href="#xxx-ref" data-toggle="tab">,
it works.
you did great job,  this is my favorte theme, thank you.

**Comment by mrichar1** [comment]
It looks like this is a bug related to app.js not expecting site.BASE_PATH to be set.

The activateTab function looks at the window location to see if it matches `/tags.html` or `/categories.html`:

``` javascript
function activateTab() {
      if(['/tags.html', '/categories.html'].indexOf(window.location.pathname) > -1) {
```

However, if `BASE_PATH` is defined, then `window.location.pathname` will be `BASE_PATH/tags.html` or `BASE_PATH/categories.html`

The code probably wants to see if the pathname ends with either of these strings, rather than being exact - something like the following (not a JS programmer by trade, so this might not be the best way of doing this, but it does work to prove the bug):

```
if((window.location.pathname.endsWith('/categories.html')) || (window.location.pathname.endsWith('/tags.html'))) {
```
